//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Team { get; set; }
        public string Position { get; set; }
        public int Yearspro { get; set; }
    }
}
